domain: ""
address: 127.0.0.1
port: 80
database_url: app.db
zmq_sms_pub: tcp://127.0.0.1:5561
zmq_clients_pub: tcp://127.0.0.1:5565
sms_sender: cns.shared
templates_dir: templates/**/*
secret: env::APP_SECRET
auth_service_url: ""
crm_service_url: ""
