name: Test and lint PRs

on:
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # needed for diff

      # Decide if Rust/Cargo files changed
      - name: Detect changed paths
        id: filter
        uses: dorny/paths-filter@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          filters: |
            rust:
              - '**/*.rs'
            cargo:
              - 'Cargo.toml'
              - 'Cargo.lock'

      # Quick no-op so the job still succeeds when nothing relevant changed
      - name: No Rust changes — skipping clippy/test
        if: ${{ steps.filter.outputs.rust != 'true' && steps.filter.outputs.cargo != 'true' }}
        run: |
          echo "No .rs or Cargo* changes in this PR. Skipping clippy/test."

      # Toolchain only if needed
      - name: Install Rust toolchain
        if: ${{ steps.filter.outputs.rust == 'true' || steps.filter.outputs.cargo == 'true' }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Run clippy
        if: ${{ steps.filter.outputs.rust == 'true' || steps.filter.outputs.cargo == 'true' }}
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all-targets --all-features -- -D warnings

      - name: Run tests
        if: ${{ steps.filter.outputs.rust == 'true' || steps.filter.outputs.cargo == 'true' }}
        uses: actions-rs/cargo@v1
        with:
          command: test
